#!/usr/bin/env bash
# This script changes the IP addresses for localhost and facebook.com

# Change localhost to 127.0.0.2
sudo sed -i 's/127.0.0.1/127.0.0.2/g' /etc/hosts

# Change facebook.com to 8.8.8.8
sudo sed -i 's/facebook.com/8.8.8.8/g' /etc/hosts

