#!/usr/bin/env bash
# This script makes localhost resolve to 127.0.0.2 and facebook.com to 8.8.8.8 on Ubuntu

sudo cp /etc/hosts /etc/hosts.bak

sudo sed -i '/localhost/d' /etc/hosts

echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts > /dev/null
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
