#!/usr/bin/env bash
# This script displays all active IPv4 addresses on the machine using ifconfig.

ifconfig | grep -oE 'inet (addr:)?([0-9]{1,3}\.){3}[0-9]{1,3}' | grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}'
